/**
 * AUTO-GENERATED by `pnpm -F i18n-studio i18n:codegen` — DO NOT EDIT BY HAND.
 *
 * Single source for the UI's supported language set, derived offline from the
 * committed `app/i18n/locales/` tree + `_meta.json`. Re-run codegen after
 * changing those; CI asserts this file is in sync.
 */
import zhCn_common from './locales/zh-cn/common.json';
import zhCn_landing from './locales/zh-cn/landing.json';
import enUs_common from './locales/en-us/common.json';
import enUs_landing from './locales/en-us/landing.json';

export const SUPPORTED_LANGS = ['zh-cn', 'en-us'] as const;

export type Lang = (typeof SUPPORTED_LANGS)[number];

export const DEFAULT_LANG: Lang = 'zh-cn';

export const I18N_NAMESPACES = ['common', 'landing'] as const;

export const resources = {
  'zh-cn': {
    common: zhCn_common,
    landing: zhCn_landing,
  },
  'en-us': {
    common: enUs_common,
    landing: enUs_landing,
  },
} as const;

export interface LocaleMeta {
  code: Lang;
  label: string;
  englishLabel: string;
  nativeLabel: string | null;
}

export const LOCALE_META: readonly LocaleMeta[] = [
  { code: 'zh-cn', label: '简体中文', englishLabel: 'Simplified Chinese', nativeLabel: '中文(简体)' },
  { code: 'en-us', label: '英语 (美国)', englishLabel: 'English (US)', nativeLabel: 'English' },
];
