/**
 * AUTO-GENERATED by `pnpm -F i18n-studio i18n:codegen` — DO NOT EDIT BY HAND.
 *
 * Single source for the UI's supported language set, derived offline from the
 * committed `app/i18n/locales/` tree + `_meta.json`. Re-run codegen after
 * changing those; CI asserts this file is in sync.
 */
import zhCn_studioUi from './locales/zh-cn/studio-ui.json';
import enUs_studioUi from './locales/en-us/studio-ui.json';

export const SUPPORTED_LANGS = ['zh-cn', 'en-us'] as const;

export type Lang = (typeof SUPPORTED_LANGS)[number];

export const DEFAULT_LANG: Lang = 'zh-cn';

export const I18N_NAMESPACES = ['studio-ui'] as const;

export const resources = {
  'zh-cn': {
    'studio-ui': zhCn_studioUi,
  },
  'en-us': {
    'studio-ui': enUs_studioUi,
  },
} as const;

export interface LocaleMeta {
  code: Lang;
  label: string;
  englishLabel: string;
  nativeLabel: string | null;
}

export const LOCALE_META: readonly LocaleMeta[] = [
  { code: 'zh-cn', label: '简体中文', englishLabel: 'Simplified Chinese', nativeLabel: '中文(简体)' },
  { code: 'en-us', label: '英语 (美国)', englishLabel: 'English (US)', nativeLabel: 'English' },
];
