packages:
  - 'packages/apps/*'
  - 'packages/libs/*'
allowBuilds:
  '@swc/core': true
  better-sqlite3: true
  bufferutil: true
  es5-ext: true
  esbuild: true
  keccak: true
  sharp: true
  utf-8-validate: true
  workerd: true
minimumReleaseAgeExclude:
  - i18next-cli@1.62.0
overrides:
  style-to-js: ^1.1.16
