/**
 * Build-time codegen: scan `app/i18n/locales/` and emit `app/i18n/generated.ts`.
 *
 * Run: `pnpm -F i18n-studio i18n:codegen`
 *
 * Source of truth is the on-disk locale tree (committed to the repo):
 *   app/i18n/locales/<lang>/<ns>.json   — nested i18next resources
 *   app/i18n/locales/_meta.json         — per-lang display metadata (label/native)
 *
 * The generated module is the SINGLE source for the UI's supported language set:
 *   - SUPPORTED_LANGS : lang codes = subdirectory names (sorted, default first)
 *   - I18N_NAMESPACES : ns names  = <ns>.json basenames (union across langs)
 *   - resources       : statically-imported bundles ({ [lang]: { [ns]: json } })
 *   - LOCALE_META     : [{ code, label, englishLabel, nativeLabel }]
 *
 * OFFLINE-FIRST: this only touches the committed file tree — no DB, no running
 * studio, no network. A fresh clone / CI build can regenerate deterministically.
 * Metadata missing from _meta.json degrades to the code itself (never throws).
 *
 * Output is deterministic (sorted keys) so the committed `generated.ts` diffs
 * cleanly and CI can assert it is up to date.
 */
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const APP_DIR = path.resolve(SCRIPT_DIR, '..');
const LOCALES_DIR = path.join(APP_DIR, 'app', 'i18n', 'locales');
const META_FILE = path.join(LOCALES_DIR, '_meta.json');
const OUT_FILE = path.join(APP_DIR, 'app', 'i18n', 'generated.ts');

/** Default/fallback UI language — listed first in SUPPORTED_LANGS. */
const DEFAULT_LANG = 'zh-cn';

interface MetaEntry {
  label?: string;
  englishLabel?: string;
  nativeLabel?: string | null;
}

/** @returns sorted lang codes, DEFAULT_LANG first if present */
function readLangs(): string[] {
  const langs = fs
    .readdirSync(LOCALES_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
  return langs.includes(DEFAULT_LANG) ? [DEFAULT_LANG, ...langs.filter((l) => l !== DEFAULT_LANG)] : langs;
}

/** @returns sorted ns names for a lang dir */
function readNamespaces(lang: string): string[] {
  return fs
    .readdirSync(path.join(LOCALES_DIR, lang))
    .filter((f) => f.endsWith('.json'))
    .map((f) => path.basename(f, '.json'))
    .sort();
}

function readMeta(): Record<string, MetaEntry> {
  if (!fs.existsSync(META_FILE)) return {};
  try {
    return JSON.parse(fs.readFileSync(META_FILE, 'utf8'));
  } catch {
    return {};
  }
}

function jsStr(s: string): string {
  return JSON.stringify(s);
}

/** Build the import identifier for a (lang, ns) pair, e.g. zh-cn/common → zhCn_common. */
function importIdent(lang: string, ns: string): string {
  const safe = (x: string): string =>
    x.replace(/[^a-zA-Z0-9]+(.)?/g, (_, c: string | undefined) => (c ? c.toUpperCase() : ''));
  return `${safe(lang)}_${safe(ns)}`;
}

function main(): void {
  if (!fs.existsSync(LOCALES_DIR)) {
    console.error(`[codegen] 资源目录不存在: ${LOCALES_DIR}`);
    process.exit(1);
  }
  const langs = readLangs();
  if (langs.length === 0) {
    console.error('[codegen] locales 下没有语言目录,无法生成');
    process.exit(1);
  }
  // namespaces = union across all langs (sorted, stable)
  const nsSet = new Set<string>();
  for (const lang of langs) for (const ns of readNamespaces(lang)) nsSet.add(ns);
  const namespaces = [...nsSet].sort();
  const meta = readMeta();

  const importLines: string[] = [];
  const resourceLangBlocks: string[] = [];
  for (const lang of langs) {
    const nsForLang = readNamespaces(lang);
    const nsEntries: string[] = [];
    for (const ns of namespaces) {
      if (!nsForLang.includes(ns)) continue;
      const ident = importIdent(lang, ns);
      importLines.push(`import ${ident} from './locales/${lang}/${ns}.json';`);
      nsEntries.push(`    ${jsStr(ns)}: ${ident},`);
    }
    resourceLangBlocks.push(`  ${jsStr(lang)}: {\n${nsEntries.join('\n')}\n  },`);
  }

  const metaEntries = langs.map((code) => {
    const m = meta[code] ?? {};
    const label = typeof m.label === 'string' ? m.label : code;
    const englishLabel = typeof m.englishLabel === 'string' ? m.englishLabel : code;
    const nativeLabel = typeof m.nativeLabel === 'string' ? m.nativeLabel : null;
    return `  { code: ${jsStr(code)}, label: ${jsStr(label)}, englishLabel: ${jsStr(englishLabel)}, nativeLabel: ${nativeLabel === null ? 'null' : jsStr(nativeLabel)} },`;
  });

  const supportedList = langs.map((l) => jsStr(l)).join(', ');
  const nsList = namespaces.map((n) => jsStr(n)).join(', ');

  const out = `/**
 * AUTO-GENERATED by \`pnpm -F i18n-studio i18n:codegen\` — DO NOT EDIT BY HAND.
 *
 * Single source for the UI's supported language set, derived offline from the
 * committed \`app/i18n/locales/\` tree + \`_meta.json\`. Re-run codegen after
 * changing those; CI asserts this file is in sync.
 */
${importLines.join('\n')}

export const SUPPORTED_LANGS = [${supportedList}] as const;

export type Lang = (typeof SUPPORTED_LANGS)[number];

export const DEFAULT_LANG: Lang = ${jsStr(DEFAULT_LANG)};

export const I18N_NAMESPACES = [${nsList}] as const;

export const resources = {
${resourceLangBlocks.join('\n')}
} as const;

export interface LocaleMeta {
  code: Lang;
  label: string;
  englishLabel: string;
  nativeLabel: string | null;
}

export const LOCALE_META: readonly LocaleMeta[] = [
${metaEntries.join('\n')}
];
`;

  fs.writeFileSync(OUT_FILE, out, 'utf8');
  console.log(
    `[codegen] 生成 ${path.relative(APP_DIR, OUT_FILE)}: ${langs.length} 语种 [${langs.join(', ')}], ${namespaces.length} namespace [${namespaces.join(', ')}]`,
  );
}

main();
